### ISSUE TITLE
Excellent work and a questions?

### ISSUE THREAD

**Issue by EllisonKuang** [likesum/deepFnF#4]
The pre-training model of this project has achieved good results, but the model trained by ourselves have not achieved ideal results. May I ask how many interations you have trained to get the pre-training model? Have the hyperparameters used been changed?

**Comment by Holomorphic** [comment]
Hi! I have some problems when extracting metadata from images. Did you run dump_exif.py directly with the dataset?

**Comment by Xinyil256** [comment]
> The pre-training model of this project has achieved good results, but the model trained by ourselves have not achieved ideal results. May I ask how many interations you have trained to get the pre-training model? Have the hyperparameters used been changed?
Hi! I have some problems when extracting metadata from images. Did you run dump_exif.py directly with the dataset?

**Comment by EllisonKuang** [comment]
> > Hi! I have some problems when extracting metadata from images. Did you run dump_exif.py directly with the dataset?

yes, you can download the illumination dataset provided in readme and run dump_exif.py.

**Comment by Holomorphic** [comment]
> 
Hi! Thanks for your reply! I've handled the dataset but met some problems when retraining the model. Have you retrained the code?
