### ISSUE TITLE
sorry for wrong issue

### ISSUE THREAD

**Issue by Xinyil256** [likesum/deepFnF#7]
Sorry for Wrong issue

**Comment by Holomorphic** [comment]
> > > Hi! I have some problems when extracting metadata from images. Did you run dump_exif.py directly with the dataset?
> 
> yes, you can download the illumination dataset provided in readme and run dump_exif.py.
> 
> _Originally posted by @SUSTechEllison in [#4 (comment)](https://github.com/likesum/deepFnF/issues/4#issuecomment-1120094261)_
